//! G17-MERGEEX — MERGE template EXPLAIN validation tests.
//!
//! These tests verify that the MERGE SQL templates generated by the DVM engine
//! are syntactically valid and accepted by PostgreSQL's planner. Each test
//! creates a stream table with a representative query pattern, performs an
//! initial populate and a differential refresh cycle, then validates that the
//! stream table matches the defining query.
//!
//! Catches malformed MERGE templates before any production data is processed.
//! Prerequisites: E2E test image (built by `just build-e2e-image`)

mod e2e;

use e2e::E2eDb;

// ── Helper: validate MERGE template via refresh + EXPLAIN ──────────────

/// Create a stream table, populate it, apply a change, refresh and verify.
/// This exercises the full MERGE template generation and execution path.
async fn validate_merge_template(
    db: &E2eDb,
    name: &str,
    setup_sql: &str,
    defining_query: &str,
    change_sql: &str,
) {
    // Setup source tables
    for stmt in setup_sql.split(';').filter(|s| !s.trim().is_empty()) {
        db.execute(stmt).await;
    }

    // Create the stream table in DIFFERENTIAL mode
    db.create_st(name, defining_query, "1h", "DIFFERENTIAL")
        .await;
    db.refresh_st(name).await;

    // Verify initial population matches the defining query
    db.assert_st_matches_query(&format!("public.{name}"), defining_query)
        .await;

    // Apply a DML change and do a differential refresh (exercises MERGE template)
    db.execute(change_sql).await;
    db.refresh_st(name).await;

    // Verify the stream table still matches after MERGE
    db.assert_st_matches_query(&format!("public.{name}"), defining_query)
        .await;

    // Validate that EXPLAIN works on the defining query (catches syntax issues)
    let explain_sql = format!("EXPLAIN (COSTS OFF) {defining_query}");
    db.execute(&explain_sql).await;
}

// ── Scan ───────────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_scan() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_scan",
        "CREATE TABLE src_scan (id INT PRIMARY KEY, val TEXT);
         INSERT INTO src_scan VALUES (1, 'a'), (2, 'b'), (3, 'c')",
        "SELECT id, val FROM src_scan",
        "UPDATE src_scan SET val = 'x' WHERE id = 1",
    )
    .await;
}

// ── Filter ─────────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_filter() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_filter",
        "CREATE TABLE src_filter (id INT PRIMARY KEY, amount INT);
         INSERT INTO src_filter VALUES (1, 100), (2, 200), (3, 50)",
        "SELECT id, amount FROM src_filter WHERE amount > 75",
        "UPDATE src_filter SET amount = 300 WHERE id = 3",
    )
    .await;
}

// ── Aggregate ──────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_aggregate() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_agg",
        "CREATE TABLE src_agg (id INT PRIMARY KEY, region TEXT, amount INT);
         INSERT INTO src_agg VALUES (1, 'US', 100), (2, 'EU', 200), (3, 'US', 50)",
        "SELECT region, SUM(amount) AS total, COUNT(*) AS cnt FROM src_agg GROUP BY region",
        "UPDATE src_agg SET amount = 150 WHERE id = 1",
    )
    .await;
}

// ── Inner Join ─────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_inner_join() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_join",
        "CREATE TABLE src_orders (id INT PRIMARY KEY, region_id INT, amount INT);
         CREATE TABLE dim_regions (id INT PRIMARY KEY, region_name TEXT);
         INSERT INTO dim_regions VALUES (1, 'US'), (2, 'EU');
         INSERT INTO src_orders VALUES (1, 1, 100), (2, 2, 200), (3, 1, 50)",
        "SELECT o.id, d.region_name, o.amount FROM src_orders o JOIN dim_regions d ON o.region_id = d.id",
        "UPDATE src_orders SET amount = 999 WHERE id = 2",
    )
    .await;
}

// ── Left Join ──────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_left_join() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_left_join",
        "CREATE TABLE src_lj (id INT PRIMARY KEY, ref_id INT);
         CREATE TABLE dim_lj (id INT PRIMARY KEY, label TEXT);
         INSERT INTO dim_lj VALUES (1, 'A'), (2, 'B');
         INSERT INTO src_lj VALUES (1, 1), (2, 2), (3, 99)",
        "SELECT s.id, d.label FROM src_lj s LEFT JOIN dim_lj d ON s.ref_id = d.id",
        "INSERT INTO src_lj VALUES (4, 1)",
    )
    .await;
}

// ── Join + Aggregate ───────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_join_agg() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_join_agg",
        "CREATE TABLE src_ja (id INT PRIMARY KEY, region_id INT, amount INT);
         CREATE TABLE dim_ja (id INT PRIMARY KEY, region_name TEXT);
         INSERT INTO dim_ja VALUES (1, 'US'), (2, 'EU');
         INSERT INTO src_ja VALUES (1, 1, 100), (2, 2, 200), (3, 1, 50)",
        "SELECT d.region_name, SUM(s.amount) AS total, COUNT(*) AS cnt \
         FROM src_ja s JOIN dim_ja d ON s.region_id = d.id GROUP BY d.region_name",
        "DELETE FROM src_ja WHERE id = 3",
    )
    .await;
}

// ── DISTINCT ───────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_distinct() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_distinct",
        "CREATE TABLE src_dist (id INT PRIMARY KEY, category TEXT);
         INSERT INTO src_dist VALUES (1, 'A'), (2, 'B'), (3, 'A')",
        "SELECT DISTINCT category FROM src_dist",
        "INSERT INTO src_dist VALUES (4, 'C')",
    )
    .await;
}

// ── UNION ALL ──────────────────────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_union_all() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_union",
        "CREATE TABLE src_union_a (id INT PRIMARY KEY, val TEXT);
         CREATE TABLE src_union_b (id INT PRIMARY KEY, val TEXT);
         INSERT INTO src_union_a VALUES (1, 'a'), (2, 'b');
         INSERT INTO src_union_b VALUES (3, 'c'), (4, 'd')",
        "SELECT id, val FROM src_union_a UNION ALL SELECT id, val FROM src_union_b",
        "INSERT INTO src_union_a VALUES (5, 'e')",
    )
    .await;
}

// ── TopK (ORDER BY + LIMIT) ───────────────────────────────────────────

#[tokio::test]
async fn test_merge_template_explain_topk() {
    let db = E2eDb::new().await.with_extension().await;
    validate_merge_template(
        &db,
        "mt_topk",
        "CREATE TABLE src_topk (id INT PRIMARY KEY, score INT);
         INSERT INTO src_topk VALUES (1, 10), (2, 50), (3, 30), (4, 90), (5, 20)",
        "SELECT id, score FROM src_topk ORDER BY score DESC LIMIT 3",
        "UPDATE src_topk SET score = 99 WHERE id = 1",
    )
    .await;
}
