name: 'dbt_pgtrickle_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

seeds:
  dbt_pgtrickle_integration_tests:
    raw_orders:
      +post-hook: "ALTER TABLE {{ this }} ADD PRIMARY KEY (id)"

clean-targets:
  - "target"
  - "dbt_packages"
