getting_started:
  target: default
  outputs:
    default:
      type: postgres
      host:     "{{ env_var('PGHOST',     'localhost') }}"
      port:     "{{ env_var('PGPORT',     '5432') | as_number }}"
      user:     "{{ env_var('PGUSER',     'postgres') }}"
      password: "{{ env_var('PGPASSWORD', 'postgres') }}"
      dbname:   "{{ env_var('PGDATABASE', 'postgres') }}"
      schema: public
      threads: 1
